name: Greenify Contributions

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 1 * * *'
    - cron: '0 2 * * *'  
    - cron: '0 3 * * *'  
    - cron: '0 4 * * *'  
    - cron: '0 5 * * *'  
    - cron: '0 7 * * *'  
    - cron: '0 10 * * *'  
    - cron: '0 15 * * *'  
    - cron: '0 17 * * *'  
    - cron: '0 20 * * *'   
  workflow_dispatch:

permissions:
  contents: write

jobs:
  greenify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run greenify script
        run: python greenify.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Hitanshu-Varia"
          git config --global user.email "variahitanshu@gmail.com"
          git add README.md
          git commit -m "🌿 Daily greenify ping" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{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}}
